CREATE TABLE "users" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "username" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "is_email_confirmed" BOOLEAN NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    "email_confirmation_token" TEXT,
    "email_confirmation_token_expiry" TIMESTAMPTZ(6),
    "email_change_token" TEXT,
    "email_change_token_expiry" TIMESTAMPTZ(6),
    "password_reset_token" TEXT,
    "password_reset_token_expiry" TIMESTAMPTZ(6),
    "pending_email" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_users_by_username" ON "users" ("username");
CREATE UNIQUE INDEX "index_users_by_email" ON "users" ("email");
CREATE TABLE "refresh_tokens" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "token" TEXT NOT NULL,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "user_id" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_refresh_tokens_by_token" ON "refresh_tokens" ("token");
CREATE INDEX "index_refresh_tokens_by_user_id" ON "refresh_tokens" ("user_id");
CREATE TABLE "files" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "filename" TEXT NOT NULL,
    "original_name" TEXT NOT NULL,
    "file_path" TEXT NOT NULL,
    "mime_type" TEXT NOT NULL,
    "encoding" TEXT NOT NULL,
    "size" BIGINT NOT NULL,
    "storage_type" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "metadata" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(6),
    "deleted_by_user_id" BIGINT,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_files_by_deleted_by_user_id" ON "files" ("deleted_by_user_id");
CREATE TABLE "user_roles" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" BIGINT NOT NULL,
    "role_id" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_user_roles_by_user_id" ON "user_roles" ("user_id");
CREATE INDEX "index_user_roles_by_role_id" ON "user_roles" ("role_id");
CREATE TABLE "users_email_history" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "old_email" TEXT NOT NULL,
    "new_email" TEXT NOT NULL,
    "email_change_at" TIMESTAMPTZ(6) NOT NULL,
    "user_id" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_users_email_history_by_user_id" ON "users_email_history" ("user_id");
CREATE TABLE "roles" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_roles_by_name" ON "roles" ("name");
