CREATE TABLE "files" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "filename" TEXT NOT NULL,
    "original_name" TEXT NOT NULL,
    "file_path" TEXT NOT NULL,
    "mime_type" TEXT NOT NULL,
    "encoding" TEXT NOT NULL,
    "size" BIGINT NOT NULL,
    "storage_type" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "metadata" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(6),
    "deleted_by_user_id" BIGINT,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_files_by_deleted_by_user_id" ON "files" ("deleted_by_user_id");
CREATE TABLE "user_roles" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" BIGINT NOT NULL,
    "role_id" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_user_roles_by_user_id" ON "user_roles" ("user_id");
CREATE INDEX "index_user_roles_by_role_id" ON "user_roles" ("role_id");
CREATE TABLE "users" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "keycloak_id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "first_name" TEXT NOT NULL,
    "last_name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_users_by_keycloak_id" ON "users" ("keycloak_id");
CREATE UNIQUE INDEX "index_users_by_email" ON "users" ("email");
CREATE TABLE "translations" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "message_key" TEXT NOT NULL,
    "message_pl" TEXT NOT NULL,
    "message_en" TEXT NOT NULL,
    "default_pl" TEXT NOT NULL,
    "default_en" TEXT NOT NULL,
    "customized" BOOLEAN NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_translations_by_message_key" ON "translations" ("message_key");
CREATE TABLE "roles" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_roles_by_name" ON "roles" ("name");
