CREATE TABLE "translations" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "message_key" TEXT NOT NULL,
    "message_pl" TEXT NOT NULL,
    "message_en" TEXT NOT NULL,
    "default_pl" TEXT NOT NULL,
    "default_en" TEXT NOT NULL,
    "customized" BOOLEAN NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_translations_by_message_key" ON "translations" ("message_key");
