[package]
name = "rust-axum-app"
version = "0.1.0"
edition = "2024"
authors = ["Mikołaj Gawron <gawrmiko@gmail.com>"]
description = "Rust Axum App"

[workspace.lints.rust]
unsafe_code = "forbid"
unused = "allow"

[lints]
workspace = true

[dependencies]
# -- Async
tokio = { version = "1.44.1", features = ["full"] }
async-trait = "0.1.87"
# -- Serde
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_with = "3.12.0"
# -- Web
axum = "0.8.1"
tower-http = { version = "0.6.2", features = ["fs"] }
tower-cookies = "0.11.0"
# -- Others
lazy-regex = "3"
strum_macros = "0.27.1"
uuid = {version = "1.15.1", features = ["v4","fast-rng",]}


[dev-dependencies]
anyhow = "1"
httpc-test = "0.1.1"