sonar.projectKey=rust-axum-app
sonar.projectName=rust-axum-app
sonar.issue.ignore.multicriteria=emailTables,emailAttributes
sonar.issue.ignore.multicriteria.emailTables.ruleKey=Web:S5257
sonar.issue.ignore.multicriteria.emailTables.resourceKey=**/templates/**/*.html
sonar.issue.ignore.multicriteria.emailAttributes.ruleKey=Web:S1827
sonar.issue.ignore.multicriteria.emailAttributes.resourceKey=**/templates/**/*.html
sonar.sources=src,resources
