version = 1

[schema]

[[schema.tables]]
id = 0
name = "users"
primary_key = { columns = [{ table = 0, index = 0 }], index = { table = 0, index = 0 } }

[[schema.tables.columns]]
id = { table = 0, index = 0 }
name = "id"
ty = "I64"
storage_ty = { Integer = 8 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 0, index = 1 }
name = "username"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 2 }
name = "email"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 3 }
name = "password_hash"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 4 }
name = "is_email_confirmed"
ty = "Bool"
storage_ty = "Boolean"

[[schema.tables.columns]]
id = { table = 0, index = 5 }
name = "is_active"
ty = "Bool"
storage_ty = "Boolean"

[[schema.tables.columns]]
id = { table = 0, index = 6 }
name = "email_confirmation_token"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 0, index = 7 }
name = "email_confirmation_token_expiry"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }
nullable = true

[[schema.tables.columns]]
id = { table = 0, index = 8 }
name = "email_change_token"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 0, index = 9 }
name = "email_change_token_expiry"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }
nullable = true

[[schema.tables.columns]]
id = { table = 0, index = 10 }
name = "password_reset_token"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 0, index = 11 }
name = "password_reset_token_expiry"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }
nullable = true

[[schema.tables.columns]]
id = { table = 0, index = 12 }
name = "pending_email"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 0, index = 13 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 0, index = 14 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.indices]]
id = { table = 0, index = 0 }
name = "index_users_by_id"
on = 0
columns = [{ column = { table = 0, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 0, index = 1 }
name = "index_users_by_username"
on = 0
columns = [{ column = { table = 0, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables.indices]]
id = { table = 0, index = 2 }
name = "index_users_by_email"
on = 0
columns = [{ column = { table = 0, index = 2 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables]]
id = 1
name = "user_roles"
primary_key = { columns = [{ table = 1, index = 0 }], index = { table = 1, index = 0 } }

[[schema.tables.columns]]
id = { table = 1, index = 0 }
name = "id"
ty = "I64"
storage_ty = { Integer = 8 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 1, index = 1 }
name = "user_id"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 1, index = 2 }
name = "role_id"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 1, index = 3 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 1, index = 4 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.indices]]
id = { table = 1, index = 0 }
name = "index_user_roles_by_id"
on = 1
columns = [{ column = { table = 1, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 1, index = 1 }
name = "index_user_roles_by_user_id"
on = 1
columns = [{ column = { table = 1, index = 1 }, op = "Eq", scope = "Partition" }]

[[schema.tables.indices]]
id = { table = 1, index = 2 }
name = "index_user_roles_by_role_id"
on = 1
columns = [{ column = { table = 1, index = 2 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 2
name = "roles"
primary_key = { columns = [{ table = 2, index = 0 }], index = { table = 2, index = 0 } }

[[schema.tables.columns]]
id = { table = 2, index = 0 }
name = "id"
ty = "I64"
storage_ty = { Integer = 8 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 2, index = 1 }
name = "name"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 2 }
name = "description"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 2, index = 3 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 2, index = 4 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.indices]]
id = { table = 2, index = 0 }
name = "index_roles_by_id"
on = 2
columns = [{ column = { table = 2, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 2, index = 1 }
name = "index_roles_by_name"
on = 2
columns = [{ column = { table = 2, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables]]
id = 3
name = "refresh_tokens"
primary_key = { columns = [{ table = 3, index = 0 }], index = { table = 3, index = 0 } }

[[schema.tables.columns]]
id = { table = 3, index = 0 }
name = "id"
ty = "I64"
storage_ty = { Integer = 8 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 3, index = 1 }
name = "token"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 2 }
name = "expires_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 3, index = 3 }
name = "user_id"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 3, index = 4 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 3, index = 5 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.indices]]
id = { table = 3, index = 0 }
name = "index_refresh_tokens_by_id"
on = 3
columns = [{ column = { table = 3, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 3, index = 1 }
name = "index_refresh_tokens_by_token"
on = 3
columns = [{ column = { table = 3, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables.indices]]
id = { table = 3, index = 2 }
name = "index_refresh_tokens_by_user_id"
on = 3
columns = [{ column = { table = 3, index = 3 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 4
name = "users_email_history"
primary_key = { columns = [{ table = 4, index = 0 }], index = { table = 4, index = 0 } }

[[schema.tables.columns]]
id = { table = 4, index = 0 }
name = "id"
ty = "I64"
storage_ty = { Integer = 8 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 4, index = 1 }
name = "old_email"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 4, index = 2 }
name = "new_email"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 4, index = 3 }
name = "email_change_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 4, index = 4 }
name = "user_id"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 4, index = 5 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 4, index = 6 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.indices]]
id = { table = 4, index = 0 }
name = "index_users_email_history_by_id"
on = 4
columns = [{ column = { table = 4, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 4, index = 1 }
name = "index_users_email_history_by_user_id"
on = 4
columns = [{ column = { table = 4, index = 4 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 5
name = "files"
primary_key = { columns = [{ table = 5, index = 0 }], index = { table = 5, index = 0 } }

[[schema.tables.columns]]
id = { table = 5, index = 0 }
name = "id"
ty = "I64"
storage_ty = { Integer = 8 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 5, index = 1 }
name = "filename"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 5, index = 2 }
name = "original_name"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 5, index = 3 }
name = "file_path"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 5, index = 4 }
name = "mime_type"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 5, index = 5 }
name = "encoding"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 5, index = 6 }
name = "size"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 5, index = 7 }
name = "storage_type"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 5, index = 8 }
name = "url"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 5, index = 9 }
name = "metadata"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 5, index = 10 }
name = "deleted_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }
nullable = true

[[schema.tables.columns]]
id = { table = 5, index = 11 }
name = "deleted_by_user_id"
ty = "I64"
storage_ty = { Integer = 8 }
nullable = true

[[schema.tables.columns]]
id = { table = 5, index = 12 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 5, index = 13 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.indices]]
id = { table = 5, index = 0 }
name = "index_files_by_id"
on = 5
columns = [{ column = { table = 5, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 5, index = 1 }
name = "index_files_by_deleted_by_user_id"
on = 5
columns = [{ column = { table = 5, index = 11 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 6
name = "translations"
primary_key = { columns = [{ table = 6, index = 0 }], index = { table = 6, index = 0 } }

[[schema.tables.columns]]
id = { table = 6, index = 0 }
name = "id"
ty = "I64"
storage_ty = { Integer = 8 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 6, index = 1 }
name = "message_key"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 6, index = 2 }
name = "message_pl"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 6, index = 3 }
name = "message_en"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 6, index = 4 }
name = "default_pl"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 6, index = 5 }
name = "default_en"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 6, index = 6 }
name = "customized"
ty = "Bool"
storage_ty = "Boolean"

[[schema.tables.columns]]
id = { table = 6, index = 7 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 6, index = 8 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.indices]]
id = { table = 6, index = 0 }
name = "index_translations_by_id"
on = 6
columns = [{ column = { table = 6, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 6, index = 1 }
name = "index_translations_by_message_key"
on = 6
columns = [{ column = { table = 6, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true
